[package]
name = "mmap-stdin"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.16.1"
memmap = "0.7.0"
memchr = "2.3.0"
